travis:
  secure:
    BINSTAR_TOKEN: Hq+mA0Vz3lKtCR8HRtCTP6NYueDcdKbBfdG0aOMP0ztWeknYVlTFDBPs77HiDAYjEf7m4KNBxxdOfmGtcR/N0NfVWBR6Ihz/+Uximq4puE1tR+p6Rmfn/eNjDdC9YvCi9PFddb7uSIul+bGuwQ9Yo8jf3ePAyRpkQB2HmgLZhRMaIh2PQcxmxsrqLadveXBPOjPpoYPMPNWk2Pe4Vi4TGRAM+C+s64tQIOQC6ThnM3N8gG1DEqRL2OvrKl1mfYdSbme6LpgcBona9uexZjN/06WkgR/wStykdPQwmykzL/eCS5ZRWI0BjbXdK4q+gvv66Bgh8amZC5Ye7aCt8SXruJB3m2r1Gw/GQNL8J+CC1+gs9y9YeattJpr7HugZMtEZIKGuY3tFnZqeTYf1m0OogFVUdshHvXSJZKVTlYewgqf7g+1IKvmEpX4yzBY3oLejQCtac23QrASy/P9RA0TG0jBHeatQBAS23lbsVbSsDtue+AC6HrTvIFxBEhpRqZcPXhnUUSq6103m4tWbzLfucVopIY1YW9LWc30hRU2RtTAyz7/E+EXUnMf37qOsZ3txDzmFh8jytnnXq4kVRIY5fgT0OCT70YsMGwxVYwHasdlxVg9lbAeiSHGyKs8bcg7m7Rn1kh/y+bC+McgBld3oqd21XCVJOp/ocFPXr3AJWeM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
