travis:
  secure:
    BINSTAR_TOKEN: UPense0vP73tbeEsrbhYMCKMFKbE4sjZDSqLRs1L8AqXc2OATEfSGsp9JfDcA+S+t5ycVdzwtYdBaAMqItGUaSBWkBdM6F3VKp7RlmpLTTFhq4kHkkbbUUfWt2UIDAcEDiglo6Cqk3Lgd5FzOfeAMuMviNQDYnI/XwcVgJuPxJ3WMOW0WTbDkcj5SeuvZrKeMdNGL3YZU3RpWAXwH7IHJHdwN2syRU1jChKCzAMiWH6vxJ6uLGlLvbBch3NuKm/BfvR3IdY8P2TcnO+PGUMW15k4KDVyC7ZJFOAr6Kjf+plO/MmpYMwoBB8DcL0FfY+4zMbqaT+Sov+6ieyuDnVHbEc21U+rAO3VsgclI24NqCH7u1rsTLSr4Sn3zf/zouQ8mP1ssi+s15wDBIQb4oaEes+JC9NoChtOC25MWPM7LNFm5+Jl1kuHLa1z8uG/BoQbU40WCS45fimMmMtNy3al/HFg00XiVuTbFOxFEHi8lkc06SaZzFNHQSHBiZpu36EM4v6hddxpfFfr0SxykEdQ7RCaL6d2pZw6TzkeDk+RkZmR8xg+j13uDE92aV3epE0ZQQYbvUFXw64qEYr3mQ9tmYmb76G6Q855IiUtyT3UFWWjyKDj4EftpteMvzMU4qs0JFPV7M5haI4wS3lz8dT/FY7Z5FNltZpTinExtBfLeqc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
