travis:
  secure:
    BINSTAR_TOKEN: Fmwf/BMBvnaER6bO5j2jY7sN7VJs2LZE4SkJs2MxpiLlRFdV1mtJLpkaKjkd38uUZ+DpryijxuEMZQoRLZKtuhrBnnxPISFPNcXqsdWVGHz7tZLx4ocf5eM7/YVyAxFyXyeO/W8VHmgPUZyfWHBFxNDxPI4O4Q9V0AXo7HCdD+i7AziZKmcxIQYqtfOwoKf4PEkKi1oM5nPditR167qullk0K4yvl+aF7EBCxncKwKUL45NUBMimvZfDwNSbB5bWoUTmMaOYTiyuIzkafjF3MCCMdC8pvElxVKxZkfUDiIFKLMxEeC0pHME6l7XCASvV3UVUhml/6I1sVzR97dOcQ0st7e916VhDjAgJvMTg05eVGFucALeXKIlJ8uiu4SZCsST4wJscvMU12497AgcZiP6I4MB0TzNkP07FQyojLgG7wWduzHedczi2MP6HYM3N4qfksFZ3ErhwpmzTlbSpoJRfmNYQDzgXPGiga2IRoFGCZsY5dfrDHlqReSZWSPuNjAhHonb7bYR5gCRSUbMEAKJiRm4EO3m+WAF6ey4JHKcmRumMMS7hvjcsjjMthtNFbfRp9CP0IdO0JWH2TvKZ214jGd0J4MnPsxQkwjmWGoo04UyhBFH+nVo8NCktpNsEJExLQjyfD4BPNL1uzIhiI0D+bwWD0pECEbN6aYkVq+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
